// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi0g_X6Dfui9D3QAsyfgpm8bS33ztfde0',
    appId: '1:239990276254:web:e6d1dce1b9dc9f41c57b8f',
    messagingSenderId: '239990276254',
    projectId: 'proverb-application',
    authDomain: 'proverb-application.firebaseapp.com',
    storageBucket: 'proverb-application.firebasestorage.app',
    measurementId: 'G-DYB1SR94PK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-H4RzaojNL7O4OZtlCsrennnuZNgYNAs',
    appId: '1:239990276254:android:c32d1fb077ca0ca9c57b8f',
    messagingSenderId: '239990276254',
    projectId: 'proverb-application',
    storageBucket: 'proverb-application.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJcyRoP3TVrhwuJ2ZDYQFN_iX7npXVPj8',
    appId: '1:239990276254:ios:85e3fd3fbb315f80c57b8f',
    messagingSenderId: '239990276254',
    projectId: 'proverb-application',
    storageBucket: 'proverb-application.firebasestorage.app',
    iosBundleId: 'com.briands.proverbapp.proverbapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJcyRoP3TVrhwuJ2ZDYQFN_iX7npXVPj8',
    appId: '1:239990276254:ios:85e3fd3fbb315f80c57b8f',
    messagingSenderId: '239990276254',
    projectId: 'proverb-application',
    storageBucket: 'proverb-application.firebasestorage.app',
    iosBundleId: 'com.briands.proverbapp.proverbapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAi0g_X6Dfui9D3QAsyfgpm8bS33ztfde0',
    appId: '1:239990276254:web:ae39a62b6a1b8fb5c57b8f',
    messagingSenderId: '239990276254',
    projectId: 'proverb-application',
    authDomain: 'proverb-application.firebaseapp.com',
    storageBucket: 'proverb-application.firebasestorage.app',
    measurementId: 'G-QZW74SJ4RS',
  );
}
